### PR TITLE
Provision for trailing widget added. 

### PR DESCRIPTION
**Pull request by SulabhShrestha**
StepperData has more fields such as title, subtitle, leading and trailing. 

title and subtitle accepts Text widget, leading and trailing accepts Widget. 
Having this makes the user more power to control over the UI. 

PS: trailing widget is only used in VerticalStepper.

### CODE REVIEW

**Comment by BrianCraig** [comment]
Hi @SulabhShrestha !
Thanks for the contribution, unfortunately i do not *own* another_stepper package on pub.dev, this repo was originally a fork, i tried to find the original repository but it's been deleted, but I'm sure was created by @rajnishsharma1.  

I do not know who is the actual owner of the pub.dev package, you can still publish another one with a different name, or use it privately.

Please check https://github.com/BrianCraig/another_stepper/network, there are multiple forks with more commit than this repo, they may actively maintain this package code.

**Comment by rajnishsharma1** [comment]
Hi, I am not getting time to maintain this package, so I made this private.

I will review it and merge it!

**Comment by loopforge** [comment]
Hi, I am not able to maintain this package now. So made it private.
Any Pull requests are welcome.

PS: I have made my repo public now.

**Comment by BrianCraig** [comment]
@SulabhShrestha Please make the PR to https://github.com/rajnishsharma1/another_stepper, thanks!

**Pull request closed without merging**
